name: droidconke2020_flutter
description: The official DroidconKE 2020 Conference App made with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  freezed_annotation:
  rxdart: ^0.24.1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.1
  flutter_svg: ^0.18.1
  url_launcher: ^5.7.10
  community_material_icon:
  clipboard_manager: ^0.0.4
  flutter_form_builder: ^3.14.1
  cached_network_image: ^2.3.3
  debug_mode: ^0.1.1
  firebase_analytics: ^6.2.0
  firebase_crashlytics: ^0.2.3
  firebase_performance: ^0.4.2
  google_sign_in: ^4.5.6
  dio_firebase_performance: ^0.2.0
  dio_http_cache: ^0.2.11
  json_serializable: any
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  hydrated_bloc: ^6.1.0
  get_it: ^5.0.1
  firebase_core: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.3
  build_runner:
  # flutter packages pub run build_runner watch --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/afrikons/


